### ISSUE TITLE
Allow use of some default font

### ISSUE THREAD

**Issue by stjahns** [PistonDevelopers/gfx_debug_draw#2]
Requiring users to provide their own bitmap font sources isn't very convenient.
Probably look at http://doc.rust-lang.org/std/macro.include_bytes!.html  and http://doc.rust-lang.org/std/macro.include_str!.html as methods of including the texture and .fnt sources in the library.

**Comment by bvssvni** [comment]
Perhaps use the font Conrod is using https://github.com/PistonDevelopers/conrod/tree/master/assets/NotoSans
