### ISSUE TITLE
Use gfx::Canvas

### ISSUE THREAD

**Issue by kvark** [PistonDevelopers/gfx_debug_draw#23]
It would be super convenient to use `Canvas` for initialization and drawing, since it replaces 3 parameters at once. Almost all of the gfx demos (as well as gfx_scene and stuff) are using Canvas now. However, using it for your example may require porting it to piston-window.

**Comment by bvssvni** [comment]
@kvark Will use of `Canvas` in library APIs make it less flexible?

**Comment by kvark** [comment]
What I want is just some additional functions to work with Canvas, so it's not going to cut off any flexibility. Besides, the example code would be much cleaner.

Regards,
Dzmitry

**Comment by bvssvni** [comment]
@kvark Yeah, that would be nice. Do you think that piston-window should use `Canvas`? I was wonder whether APIs using `Canvas` works with those without it and vice versa.

**Comment by kvark** [comment]
I believe piston-window and Canvas are made for each other.

APIs for the Canvas are not backwards compatible, so they need to be built on top of lower level interfaces, which operate with devices or factories directly.

Regards,
Dzmitry

**Comment by bvssvni** [comment]
@kvark Thanks for the info!

**Comment by stjahns** [comment]
Trying to get this working, don't think they are playing together quite nicely yet.

Looks to me like piston_window::Gfx should be replaced with gfx::Canvas? Otherwise I'm not sure how to to get a Canvas and a PistonWindow at the same time.

**Comment by stjahns** [comment]
I'll try whipping up a PR for PistonWindow trying this ...
