### ISSUE TITLE
Consider implicit batches

### ISSUE THREAD

**Issue by kvark** [PistonDevelopers/gfx_debug_draw#6]
Since you are composing batches on the fly and not storing them (correct me if this is wrong), you could use implicit batches when rendering. See the [triangle](https://github.com/gfx-rs/gfx_examples/blob/master/src/triangle/main.rs#L107) example for the reference:

``` rust
renderer.draw(&gfx::batch::bind(&state, &mesh, slice.clone(), &program, &None), &frame).unwrap();
```

It wouldn't make much difference to you, it would just clean up a bit of code probably. A better approach would be to actually store the batches, thus taking benefit of the on-init checks.

**Comment by stjahns** [comment]
That's better https://github.com/PistonDevelopers/gfx-debug-draw/pull/7. Thanks for taking a look at this :)
