### ISSUE TITLE
Update to latest Gfx

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_debug_draw#62]
I have it almost working locally, but blocked by https://github.com/gfx-rs/gfx/issues/972.

This might require a change to the gfx_text library (and probably gfx_texture, gfx_graphics and piston_window).

**Comment by kvark** [comment]
Why is this blocked?

**Comment by bvssvni** [comment]
The gfx_text library uses `Rgba8` https://github.com/PistonDevelopers/gfx_text/blob/master/src/lib.rs#L551, which is used by gfx_debug_draw. However, piston_window uses `Srgba8`, so the libraries does not work together for gfx_debug_draw.

**Comment by kvark** [comment]
Hmm, so the idea is that `gfx_text` doesn't know in advance the type of the color surface it's going to be rendering to? It could use [RawRenderTarget](https://github.com/gfx-rs/gfx/blob/master/src/render/src/pso/target.rs#L35)` then, which receives the target format in the init struct (at run-time).

**Comment by bvssvni** [comment]
What if you needed generics anyway? Or what if you implement the traits for a new type?

**Comment by kvark** [comment]
> What if you needed generics anyway?

I'm not saying the generic way is bad. It would be totally awesome to get! But so far I don't see a way to do it. So I suggested a workaround.

> Or what if you implement the traits for a new type?

Which traits?

**Comment by bvssvni** [comment]
Never mind the traits. I thought about custom formats and such.

Could try `RawRenderTarget` and see if it works.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/gfx_debug_draw/pull/63
